BetaJ/estimate_beta_j.py

This PR fixes a typos in the calculation of numerical derivatives pointed out by @jwal1024

Fix numerical derivative typo

---

ogusa_calibrate/data/PSID/psid_download.R

Fixes #20, removes `num_children` and `num_children_away_from_home`, available for only 1 and 2 years of data respectively. Adds `num_family` with the total number of family members with data for nearly every year.

Change the demographic variables pulled from PSID

---

PSL_catalog.json

This PR updates the `start_header` and `end_header` values in `PSL_catalog.json` to corresponds to the new order of sections in `README.md`.

update header start and end

---

ogusa/calibrate.py

This PR updates the URL for the matplotlib style file.  I *think* this will stop the warnings that appeared when trying to look for a style file at the previous URL.  Note that this URL is referenced because, to my knowledge, a style file can't be part of a python package (e.g., OG-Core).
At some point, we may want each country model to have it's own style file (e.g., with country-specific colors).  But this should help in the meantime.

update style file url

---

environment.yml
ogusa/deterministic_profiles.py
ogusa/income.py

The current `taxcalc` package's use of `numba` is not compatible with `numpy 1.22.2`. I tried a clean install tonight of the `ogusa-dev` conda environment using the current [`environment.yml`](https://github.com/PSLmodels/OG-USA/blob/master/environment.yml) file. After activating the new `ogusa-dev` conda environment and running `pip install -e .`, I tried to run the example script [`run_og_usa.py`](https://github.com/PSLmodels/OG-USA/blob/master/examples/run_og_usa.py). This script immediately generated the following traceback error.
```
(ogusa-dev) richardevans@Rick-MacBook-Pro-2020 OG-USA % python ./examples/run_og_usa.py
Traceback (most recent call last):
File "/Users/richardevans/Documents/Economics/OSE/OG-USA/./examples/run_og_usa.py", line 6, in <module>
from taxcalc import …
```

Added numpy<=1.21.2 constraint to environment.yml

---

docs/book/_config.yml
docs/book/content/OGUSA_references.md
docs/book/content/api/public_api.rst
docs/book/content/calibration/tax_functions.md
docs/book/content/contributing/contributor_guide.md
docs/book/content/intro/intro.md

This PR implements the following updates to the documentation.
* Update the copyright year in `_config.yml`
* Differentiate directories from the package with slashes (`public_api.rst`, `contributor_guide.md`)
* Update the BibTeX reference style.
* Basic stylistic and typographical changes.
cc: @jdebacker

Update OG-USA documentation

---

.github/workflows/deploy_docs.yml

This PR fixes the path name for the repository in the `deploy_docs.yml`. I think this was causing any updates in the documentation to not deploy to the GitHub Jupyter Book upon pushes to the master branch.
cc: @jdebacker

Fixed repo path name in deploy_docs.yml

---

ogusa/calibrate.py

This PR updates the `Calibration` class object to avoid errors when reading in tax functions from a saved pickle file.

Reading cached tax functions

---

examples/run_og_usa.py

- Explicitly set n_workers for LocalCluster creation (through Client). If this is not set, for machines with a high CPU count, the number of workers will be much larger than 7. In `client.scatter` with `broadcast=True`, this can cause hangs due to how dask distributed works. It's presumed that this bug is only apparent in more recent runs on machines with high CPU counts, although that is not confirmed. But, this fix does allow the example to run to completion on a machine with CPU_COUNT=128.

Set n_workers for dask LocalCluster

---

examples/run_og_usa.py

Following up on PR #85, I noticed that despite this changes I was again seeing memory warnings:
```
2024-02-08 09:49:00,004 - distributed.utils_perf - WARNING - full garbage collections took 14% CPU time recently (threshold: 10%)
```
And no, or slow, progress in when running `run_og_usa.py` when running with OG-Core 0.11.0 (which increases the size of several objects in the `Specifications` class object that contains the model parameters.
After some profiling, I noticed that the "bytes stored" in the `dask` processes became quite large with the tax function estimation, but then remained quite high after that task completed:  
This PR helps deal with that issue by closing and deleting the client after tax function estimation and then instantiating a new client before the model solution …

Dealing with Dask memory issues in the run script, #2

---

cs-config/cs_config/functions.py

This PR updates the Compute Studio config files to work with the latest changes to OG-USA and OG-Core.
It also adds a table showing the dynamic revenue estimate over the budget window.

Updates to CS config files

---

cs-config/cs_config/functions.py

This PR filters out those OG-USA parameters that are large or cannot be separately adjusted so that they are not available on C/S app input pages.

Filter parameters for C/S apps

---

ogusa/bequest_transmission.py
ogusa/calibrate.py
ogusa/labor.py
ogusa/transfer_distribution.py

This PR turns off all plots in the calibration files as the default.  The `run_og_usa.py` script still produces and saves some plots of the output to disk after the baseline and reform runs complete.
cc @talumbau @rickecon

Turn off plotting by default

---

examples/run_og_usa.py

This reduces run time of TPI on 64 physical core AMD workstation from ~12 hours to ~3 hours. It looks like the default of Dask is to oversubscribe threads to cores. This is not a good default for computationally intensive workloads.

Client gets threads_per_worker=1

---

cs-config/cs_config/functions.py

It looks like we are running into some  memory issues. Attempting to resolve the following error:
```
async task https://workers.ofralabs.net/api/v1/jobs/callback/3e976dbf-0b59-4baa-bbaf-96d3c20f75b9/ <function sim at 0x79d699030d60> None
getting task_kwargs
got task_kwargs {'meta_param_dict': {'year': [{'value': 2024}], 'time_path': [{'value': False}], 'data_source': [{'value': 'CPS'}]}, 'adjustment': {'OG-USA Parameters': {}, 'Tax-Calculator Parameters': {}}}
Meta_param_dict =  {'year': [{'value': 2024}], 'time_path': [{'value': False}], 'data_source': [{'value': 'CPS'}]}
adjustment dict =  {'OG-USA Parameters': {}, 'Tax-Calculator Parameters': {}}
/opt/conda/lib/python3.11/site-packages/distributed/client.py:3157: UserWarning: Sending large graph of size 246.75 MiB.
This may cause some …
```

Reduce the number of workers on CS from 5 to 3

---

.github/workflows/build_and_test.yml
examples/run_og_usa.py
examples/run_og_usa_current_policy_baseline.py

This PR makes the following updates to the example run scripts:
1. Saves all plot and table output a single folder
2. Saves a table with the full time series of several macro aggregates
3. Uses non-age specific tax functions (important given the high variation across age in functions estimated on recent versions of TaxData/Tax-Calculator (see Issue #96)

Updates to example scripts

---

.github/workflows/build_and_test.yml
CHANGELOG.md
environment.yml
ogusa/psid_data_setup.py
setup.py

This PR:
- Updates the dependency `rpy2>=3.5.12` in `environment.yml` and `setup.py`. This is meant to fix the error below in installing OG-USA in another repository.
- Moves the `rpy2` package download out of the `conda-forge` channel in the `environment.yml` file into the `pip` download section.
- Updates the rpy2 API commands in `psid_data_setup.py`.
- Adds `wheel` package to `environment.yml` dependencies. It was already in `setup.py`.
- Adds installation of R in `build_and_test.yml`
cc: @jdebacker

Updated ryp2 dependency

---

ogusa/growfactor_update.py

This PR adds a module with utilities to update the growth factors used to extrapolate micro data in the Tax-Calculator model.  The functions use output from OG-USA to update the growth factors to reflect macroeconomic outcome consistent with a particular OG-USA simulation.

Module to update `taxcalc` grow factors

---

ogusa/ogusa_default_parameters.json

This PR changes the name of the variable `AIME_num_years` to `avg_earn_num_years`, as was introduced in OG-Core version 0.11.13.

Update variable name for OG-Core 0.11.13

---

CHANGELOG.md
environment.yml
examples/run_og_usa.py
ogusa/__init__.py
ogusa/calibrate.py
ogusa/get_micro_data.py
ogusa/macro_params.py
ogusa/psid_data_setup.py
ogusa/utils.py
setup.py
tests/test_calibrate.py
tests/test_get_micro_data.py

This PR cleans up the `run_og_usa.py` script, making it clearer and saving output a common directory.

Updates to `run_og_usa.py`

---

.github/workflows/build_and_test.yml
.github/workflows/deploy_docs.yml
.github/workflows/docs_check.yml

This PR updates the miniconda installer version to miniconda instead of mambaforge in our GitHub Actions. See Issue #124. Mambaforge is being deprecated and will begin to cause more and more onerous problems and delays in our GH Actions until January 2025 when it will completely stop working (see this blog post "[Sunsetting Mambaforge](https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/)").
The change is one line in three GH Actions, as recommended in the [setup-miniconda README.md](https://github.com/conda-incubator/setup-miniconda).
cc: @jdebacker

Updated miniconda version in GH Actions

---

.gitignore
examples/run_current_policy_baseline.py

This PR:
- Updates the folder to which output gets saved (to `Example-CP`) in the `run_current_policy_baseline.py` run script. This makes that output folder inline with the other example output folders.
- Updates the `.gitignore `entry that ignores the above output.
I ran all the CI tests for this locally on my machine with a fresh `ogusa-dev` conda environment.
```
(ogusa-dev) richardevans@Richards-MacBook-Pro-5 OG-USA % pytest   
==================================== test session starts ====================================
platform darwin -- Python 3.10.17, pytest-8.3.5, pluggy-1.5.0
rootdir: /Users/richardevans/Docs/Economics/OSE/OG/OG-USA
configfile: pytest.ini
testpaths: ./tests
plugins: cov-6.1.1, xdist-3.6.1
collected 38 items …
```

Update example script and .gitignore
